#!/bin/bash

# Exit if a command returns a non-zero code
set -e

set -x

# Store the versions
VERSION=$(git describe --tags --match "v[0-9]*" --abbrev=0 | sed 's/^v//')
HEAD="f5e840748652642a4429dd78d0c2fba197b49aa2"
REPO=https://x-access-token:${OCTOKITBOT_PAT}@github.com/MaximDevoir/probot.io.git

# Generate docs
# npm run doc

# Checkout the website into the tmp directory
[ -d tmp/website ] || {
  mkdir -p tmp
  git clone "$REPO" tmp/website
}

# Update the website checkout
cd tmp/website
git pull origin master

# Delete previously generated docs for this version
rm -rf "api/$VERSION"

# Copy over the new docs
# mv ../../out "api/$VERSION"

# Update the /api/latest link to point to this version
ln -sfn "$VERSION" api/latest

# Update the submodule
git submodule update --init
cd _submodules/probot
git fetch
git checkout "$HEAD"
cd ../..

# Configure Git and Commit, and publish
git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
git config --global user.name "$GITHUB_ACTOR"
git add .
git commit -m "Update docs for v$VERSION"
git push "$REPO" master
